version: '3'
services:
  web:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "12500:12500"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 12500  --reload
  